  # 1/16/24
name: recoil-and-bounce
services:
  # Primary postgres instance with a database named recoil 
  # note that upon startup, the recoil database is seeded with
  # an employee database containing a healthy amount of data.
  postgres-primary:
    image: bitnami/postgresql:17
    container_name: postgres-primary
    # Uncomment the following two lines if you want backdoor access
    # to the primary - follow the directions in the README to see connection 
    # pooling in action, for example.
    ports:
      - "49149:5432"
    environment:
      - POSTGRES_PASSWORD=recoil
      - POSTGRESQL_REPLICATION_MODE=master  
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_DATABASE=recoil
      - POSTGRESQL_EXTRA_FLAGS=-c wal_level=logical -c max_wal_size=4GB -c min_wal_size=1GB
    networks:
      - recoil-db
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./employees_data.sql:/docker-entrypoint-initdb.d/init.sql
  # Read Replica 
  # note that no port is exposed so it'll only be available via 
  # pgbouncer via a named database (recoil-ro)
  postgres-replica:
    image: bitnami/postgresql:17
    container_name: postgres-replica
    restart: always
    depends_on:
      postgres-primary:
        condition: service_healthy
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=recoil
      - POSTGRESQL_MASTER_HOST=postgres-primary
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
    networks:
      - recoil-db
    volumes:
      - postgres-replica:/var/lib/postgresql/data
  pgcat:
    image: ghcr.io/postgresml/pgcat:v1.2.0
    restart: unless-stopped
    ports:
      - 6432:6432
      - 9930:9930
    volumes:
      - ./pgcat.toml:/etc/pgcat/pgcat.toml:ro
    networks:
      - recoil-db

networks:
  recoil-db:
    external: true

volumes:
  postgres:
  postgres-replica:
